### ISSUE TITLE
Duplicate project?

### ISSUE THREAD

**Issue by uberhacker** [DimeZilla/terminus-env-extend#1]
@DimeZilla: Are you aware of https://github.com/terminus-plugin-project/terminus-pancakes-plugin?

**Comment by DimeZilla** [comment]
welp - i saw that and thought that it was just going to try and load a gui. I just wanted the cli which the readme clearly states it supports... womp womp

**Comment by DimeZilla** [comment]
OK @uberhacker , I added env:sftp to open the sftp command - which I know the terminus filer plugin has but still I wanted it all in one place.

Secondly, unlike pancackes, this plugin allows you execute a sql query from the command line without opening the interactive command. So you can do this:

```
$ terminus env:mysql [site].[env] -- "[SQL COMMAND]"
```

I know its only a minor addition, and sure I should submit it as a feature request to pancakes, which I will, but I'm still pretty darn proud of my self for figuring all this out as it is my first terminus plugin. So well I guess I'll just chalk it up as one of my countless throwaway projects.

Thanks for viewing!

**Comment by uberhacker** [comment]
Hey @DimeZilla: We all have to start somewhere.  If you are interested, I can invite you to join https://github.com/terminus-plugin-project where you can help improve existing or add new projects.  I created this project to help consolidate all the Terminus plugins outside the Pantheon realm.

**Comment by DimeZilla** [comment]
@uberhacker - that would be awesome! Thanks! I'm very interested in doing more with terminus! Especially since the web firm I work for hosts many sites on pantheon.
